const SCHEMAS_CLIENT_API_VERSION = '2019-12-02';

const NOT_FOUND_RESPONSE_CODE = 'NotFoundException';
const BAD_REQUEST_RESPONSE_CODE = 'BadRequestException';
const NOTHING_TO_UPDATE_RESPONSE_MESSAGE = 'Invalid request. Please provide at least one field to update.';

module.exports = {
	SCHEMAS_CLIENT_API_VERSION,
	NOT_FOUND_RESPONSE_CODE,
	BAD_REQUEST_RESPONSE_CODE,
	NOTHING_TO_UPDATE_RESPONSE_MESSAGE,
};
